# permissions for end users to view simplepods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplepod-viewer-role
rules:
- apiGroups:
  - medium.callepuzzle.com
  resources:
  - simplepods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - medium.callepuzzle.com
  resources:
  - simplepods/status
  verbs:
  - get
